project:
  type: website
  output-dir: docs  

website:
  title: "Data Feminism"
  site-url: "atheobold.github.io/data-feminism/"

  navbar:
    title: "Data Feminism"
    logo: "images/plain-hex-transparent.png"
    logo-alt: "A hexagon logo for the Data Feminism course that will direct you back to the homepage (with the course description)."
    search: true
    right:
      - text: "Home"
        href: index.qmd
        #icon: house-door-fill
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Assignments"
        href: assignments.qmd
      - icon: github
        href: https://github.com/atheobold/data-feminism
        aria-label: "View source code on GitHub"

  page-footer: |
    <div style="text-align:center; font-size:0.85em;">
      ![](images/course-hex.png){width=50px fig-alt="A hexagon with a black outline and a pattern of blue, purple, and pink squares in the center. The center of the hexagon says data feminism in cursive writing."} &copy; 2026 Allison Theobold. Built with love and <a href="https://quarto.org">Quarto</a>
      
    </div>
    
  favicon: "images/plain-hex-transparent.png"

format:
  html:
    theme:
      - cosmo            
      - default          
    toc: true            
    toc-location: left   
    css: styles.css      

page-navigation: true
back-to-top-navigation: true
